### ISSUE TITLE
New.vue word added, but causes node to crash

### ISSUE THREAD

**Issue by adamfhelm** [jameshibbard/vocab-builder#13]
New.vue line 21 needs to be changed to:

this.$router.push(`/words/${res.word._id}`);

**Comment by jameshibbard** [comment]
Thanks. I'll take a look

**Comment by jameshibbard** [comment]
Ah ok, I see. 

Originally, when a word was created, it redirected to the newly created word (`res.word._id`). 

However, this turned out to be a bit of a PITA if you wanted to create multiple words, as from the newly created word, you'd need to click _New_ each time, so I changed it.

Thanks for taking the time to point that out though :)
